
# these settings. You can define environment variables
# command = "make publish"
# publish = ".docz/"
[context.production]
  environment = { NODE_VERSION = "v18.9.1" }

# export NODE_OPTIONS=--openssl-legacy-provider